export const metadata = {
    title: 'Profile || Next Hero',
    description: 'Generated by Next Hero',
  }
  
const ProfilePage = () => {
    return (
        <div>
            <h2>this is profile page</h2>
        </div>
    );
};

export default ProfilePage;