export const metadata = {
    title: 'Add Product || Dashboards || Next Hero',
    description: 'Generated by Next Hero',
  }


const AddProductPage = () => {
    return (
        <div>
            add product
        </div>
    );
};

export default AddProductPage;