export const metadata = {
    title: 'About || Next Hero',
    description: 'Generated by Next Hero',
  }

const AboutPage = () => {
    return (
        <div>
            <h2>about page</h2>
        </div>
    );
};

export default AboutPage;