export const metadata = {
    title: 'Dashboard || Next Hero',
    description: 'Generated by Next Hero',
}


const DashboardLayout = ({ children }) => {
    return (
        <div>
            <div>sidebar</div>
            {children}
        </div>
    );
};

export default DashboardLayout;